name: Launch EC2 instance

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

env: 
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    
jobs:
    build:
      name: Display running instances
      runs-on: ubuntu-latest
      steps:
      - run: sudo apt-get update
      - run: sudo apt-get install awscli -y
      - run: aws ec2 describe-instances --region us-east-1

